{{ if .crossplane.enabled -}}
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: xp-getting-started-with-aws
spec:
  ignoreCrossplaneConstraints: false
  package: registry.upbound.io/xp/getting-started-with-aws:v1.4.2
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
{{- end }}
