{{ if .crossplane.enabled -}}
---
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMUser
metadata:
  name: crossplane-iam-demo
  labels:
    gimlet: "true"
spec:
  forProvider:
    tags:
      - key: k1
        value: gimlet
  providerConfigRef:
    name: default
{{- end }}