{{- if or .Loki.Enabled .Prometheus.Enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-grafana-datasources
  namespace: infrastructure
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    {{- if .Loki.Enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      version: 1
    - name: LokiMetrics
      type: prometheus
      access: proxy
      url: http://loki:3100/loki
      version: 1
    {{- end }}
    {{- if .Prometheus.Enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      version: 1
    {{- end }}
{{- end }}