{{ if .kyverno.enabled -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: infrastructure
spec:
  interval: 60m
  url: https://kyverno.github.io/kyverno
{{- end }}
