{{- if .Linkerd.Enabled }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd
  namespace: infrastructure
spec:
  interval: 60m
  url: https://helm.linkerd.io/stable
{{- end }}
