{{ if .crossplane.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: crossplane
      interval: 10m
  values:
    leaderElection: "true"
{{- end }}
